# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import chat_pb2 as proto_dot_chat__pb2


class CentralServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/CentralServer/Heartbeat',
                request_serializer=proto_dot_chat__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.Empty.FromString,
                )
        self.RegisterClient = channel.unary_unary(
                '/CentralServer/RegisterClient',
                request_serializer=proto_dot_chat__pb2.RegisterRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.RegisterResponse.FromString,
                )
        self.GetClientInfo = channel.unary_unary(
                '/CentralServer/GetClientInfo',
                request_serializer=proto_dot_chat__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.GetInfoResponse.FromString,
                )


class CentralServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClientInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CentralServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_chat__pb2.Empty.FromString,
                    response_serializer=proto_dot_chat__pb2.Empty.SerializeToString,
            ),
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=proto_dot_chat__pb2.RegisterRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.RegisterResponse.SerializeToString,
            ),
            'GetClientInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClientInfo,
                    request_deserializer=proto_dot_chat__pb2.GetInfoRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.GetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CentralServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CentralServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralServer/Heartbeat',
            proto_dot_chat__pb2.Empty.SerializeToString,
            proto_dot_chat__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralServer/RegisterClient',
            proto_dot_chat__pb2.RegisterRequest.SerializeToString,
            proto_dot_chat__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClientInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CentralServer/GetClientInfo',
            proto_dot_chat__pb2.GetInfoRequest.SerializeToString,
            proto_dot_chat__pb2.GetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/ClientService/Heartbeat',
                request_serializer=proto_dot_chat__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.Empty.FromString,
                )
        self.Connection = channel.unary_unary(
                '/ClientService/Connection',
                request_serializer=proto_dot_chat__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.ConnectionResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/ClientService/SendMessage',
                request_serializer=proto_dot_chat__pb2.Message.SerializeToString,
                response_deserializer=proto_dot_chat__pb2.Response.FromString,
                )


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_chat__pb2.Empty.FromString,
                    response_serializer=proto_dot_chat__pb2.Empty.SerializeToString,
            ),
            'Connection': grpc.unary_unary_rpc_method_handler(
                    servicer.Connection,
                    request_deserializer=proto_dot_chat__pb2.ConnectionRequest.FromString,
                    response_serializer=proto_dot_chat__pb2.ConnectionResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=proto_dot_chat__pb2.Message.FromString,
                    response_serializer=proto_dot_chat__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/Heartbeat',
            proto_dot_chat__pb2.Empty.SerializeToString,
            proto_dot_chat__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Connection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/Connection',
            proto_dot_chat__pb2.ConnectionRequest.SerializeToString,
            proto_dot_chat__pb2.ConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/SendMessage',
            proto_dot_chat__pb2.Message.SerializeToString,
            proto_dot_chat__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
